export interface PosCategory {
  key: string;
  label: string;
  tags: { value: string; label: string }[];
}

export const posCategories: PosCategory[] = [
  {
    key: 'nouns',
    label: 'Nouns',
    tags: [
      { value: 'n', label: 'Noun' },
      { value: 'n-adv', label: 'Adverbial noun' },
      { value: 'n-t', label: 'Temporal noun' },
      { value: 'n-pr', label: 'Proper noun' },
      { value: 'n-pref', label: 'Noun prefix' },
      { value: 'n-suf', label: 'Noun suffix' },
    ],
  },
  {
    key: 'verbs',
    label: 'Verbs',
    tags: [
      { value: 'v1', label: 'Ichidan' },
      { value: 'v1-s', label: 'Ichidan (kureru)' },
      { value: 'v5u', label: 'Godan -u' },
      { value: 'v5k', label: 'Godan -ku' },
      { value: 'v5k-s', label: 'Godan -ku (iku/yuku)' },
      { value: 'v5s', label: 'Godan -su' },
      { value: 'v5r', label: 'Godan -ru' },
      { value: 'v5r-i', label: 'Godan -ru (irregular)' },
      { value: 'v5b', label: 'Godan -bu' },
      { value: 'v5g', label: 'Godan -gu' },
      { value: 'v5m', label: 'Godan -mu' },
      { value: 'v5n', label: 'Godan -nu' },
      { value: 'v5t', label: 'Godan -tsu' },
      { value: 'v5aru', label: 'Godan -aru' },
      { value: 'v5u-s', label: 'Godan -u (special)' },
      { value: 'v5uru', label: 'Godan -uru (old Eru)' },
      { value: 'vs', label: 'Suru verb' },
      { value: 'vs-i', label: 'Suru (included)' },
      { value: 'vs-s', label: 'Suru (special)' },
      { value: 'vs-c', label: 'Su verb (pre-suru)' },
      { value: 'vk', label: 'Kuru verb' },
      { value: 'vz', label: 'Ichidan -zuru' },
      { value: 'vn', label: 'Irregular -nu' },
      { value: 'vr', label: 'Irregular -ru (-ri)' },
      { value: 'v-unspec', label: 'Verb (unspecified)' },
      { value: 'vi', label: 'Intransitive' },
      { value: 'vt', label: 'Transitive' },
    ],
  },
  {
    key: 'adjectives',
    label: 'Adjectives',
    tags: [
      { value: 'adj-i', label: 'i-adjective' },
      { value: 'adj-ix', label: 'i-adjective (yoi/ii)' },
      { value: 'adj-na', label: 'na-adjective' },
      { value: 'adj-no', label: 'no-adjective' },
      { value: 'adj-pn', label: 'Pre-noun adjectival' },
      { value: 'adj-f', label: 'Prenominal' },
      { value: 'adj-t', label: 'taru-adjective' },
      { value: 'adj-nari', label: 'nari-adjective (archaic)' },
      { value: 'adj-kari', label: 'kari-adjective (archaic)' },
      { value: 'adj-ku', label: 'ku-adjective (archaic)' },
      { value: 'adj-shiku', label: 'shiku-adjective (archaic)' },
    ],
  },
  {
    key: 'adverbs',
    label: 'Adverbs',
    tags: [
      { value: 'adv', label: 'Adverb' },
      { value: 'adv-to', label: 'Adverb (to)' },
    ],
  },
  {
    key: 'expressions',
    label: 'Expressions',
    tags: [
      { value: 'exp', label: 'Expression' },
      { value: 'id', label: 'Idiomatic' },
      { value: 'proverb', label: 'Proverb' },
      { value: 'yoji', label: 'Yojijukugo' },
    ],
  },
  {
    key: 'particles',
    label: 'Particles & Grammar',
    tags: [
      { value: 'prt', label: 'Particle' },
      { value: 'conj', label: 'Conjunction' },
      { value: 'aux', label: 'Auxiliary' },
      { value: 'aux-v', label: 'Auxiliary verb' },
      { value: 'aux-adj', label: 'Auxiliary adjective' },
      { value: 'cop', label: 'Copula' },
      { value: 'int', label: 'Interjection' },
    ],
  },
  {
    key: 'affixes',
    label: 'Affixes & Counters',
    tags: [
      { value: 'pref', label: 'Prefix' },
      { value: 'suf', label: 'Suffix' },
      { value: 'ctr', label: 'Counter' },
      { value: 'num', label: 'Numeric' },
    ],
  },
  {
    key: 'classical-verbs',
    label: 'Classical verbs',
    tags: [
      { value: 'v2a-s', label: 'Nidan -u' },
      { value: 'v2b-k', label: 'Nidan -bu (upper)' },
      { value: 'v2b-s', label: 'Nidan -bu (lower)' },
      { value: 'v2d-k', label: 'Nidan -dzu (upper)' },
      { value: 'v2d-s', label: 'Nidan -dzu (lower)' },
      { value: 'v2g-k', label: 'Nidan -gu (upper)' },
      { value: 'v2g-s', label: 'Nidan -gu (lower)' },
      { value: 'v2h-k', label: 'Nidan -fu (upper)' },
      { value: 'v2h-s', label: 'Nidan -fu (lower)' },
      { value: 'v2k-k', label: 'Nidan -ku (upper)' },
      { value: 'v2k-s', label: 'Nidan -ku (lower)' },
      { value: 'v2m-k', label: 'Nidan -mu (upper)' },
      { value: 'v2m-s', label: 'Nidan -mu (lower)' },
      { value: 'v2n-s', label: 'Nidan -nu (lower)' },
      { value: 'v2r-k', label: 'Nidan -ru (upper)' },
      { value: 'v2r-s', label: 'Nidan -ru (lower)' },
      { value: 'v2s-s', label: 'Nidan -su (lower)' },
      { value: 'v2t-k', label: 'Nidan -tsu (upper)' },
      { value: 'v2t-s', label: 'Nidan -tsu (lower)' },
      { value: 'v2w-s', label: 'Nidan -u/-we (lower)' },
      { value: 'v2y-k', label: 'Nidan -yu (upper)' },
      { value: 'v2y-s', label: 'Nidan -yu (lower)' },
      { value: 'v2z-s', label: 'Nidan -zu (lower)' },
      { value: 'v4b', label: 'Yodan -bu' },
      { value: 'v4g', label: 'Yodan -gu' },
      { value: 'v4h', label: 'Yodan -fu' },
      { value: 'v4k', label: 'Yodan -ku' },
      { value: 'v4m', label: 'Yodan -mu' },
      { value: 'v4n', label: 'Yodan -nu' },
      { value: 'v4r', label: 'Yodan -ru' },
      { value: 'v4s', label: 'Yodan -su' },
      { value: 'v4t', label: 'Yodan -tsu' },
    ],
  },
  {
    key: 'names-people',
    label: 'Names (people)',
    tags: [
      { value: 'surname', label: 'Surname' },
      { value: 'name-fem', label: 'Female given name' },
      { value: 'name-masc', label: 'Male given name' },
      { value: 'given', label: 'Given name (unspecified)' },
      { value: 'person', label: 'Full person name' },
      { value: 'char', label: 'Character' },
      { value: 'dei', label: 'Deity' },
      { value: 'creat', label: 'Creature' },
    ],
  },
  {
    key: 'names-other',
    label: 'Names (other)',
    tags: [
      { value: 'place', label: 'Place name' },
      { value: 'station', label: 'Railway station' },
      { value: 'organization', label: 'Organization' },
      { value: 'company', label: 'Company' },
      { value: 'product', label: 'Product' },
      { value: 'work', label: 'Work of art' },
      { value: 'serv', label: 'Service' },
      { value: 'ship', label: 'Ship' },
      { value: 'group', label: 'Group' },
      { value: 'ev', label: 'Event' },
      { value: 'doc', label: 'Document' },
      { value: 'obj', label: 'Object' },
      { value: 'myth', label: 'Mythology' },
      { value: 'leg', label: 'Legend' },
      { value: 'fict', label: 'Fiction' },
      { value: 'relig', label: 'Religion' },
      { value: 'oth', label: 'Other name' },
      { value: 'unclass', label: 'Unclassified name' },
    ],
  },
  {
    key: 'other',
    label: 'Other',
    tags: [
      { value: 'pn', label: 'Pronoun' },
      { value: 'unc', label: 'Unclassified' },
      { value: 'on-mim', label: 'Onomatopoeia' },
    ],
  },
  {
    key: 'register',
    label: 'Register & tone',
    tags: [
      { value: 'hon', label: 'Honorific (sonkeigo)' },
      { value: 'hum', label: 'Humble (kenjougo)' },
      { value: 'pol', label: 'Polite (teineigo)' },
      { value: 'form', label: 'Formal / literary' },
      { value: 'poet', label: 'Poetical' },
      { value: 'col', label: 'Colloquial' },
      { value: 'fam', label: 'Familiar' },
      { value: 'chn', label: "Children's language" },
      { value: 'joc', label: 'Jocular' },
      { value: 'euph', label: 'Euphemistic' },
      { value: 'sl', label: 'Slang' },
      { value: 'net-sl', label: 'Internet slang' },
      { value: 'm-sl', label: 'Manga slang' },
      { value: 'derog', label: 'Derogatory' },
      { value: 'vulg', label: 'Vulgar' },
      { value: 'sens', label: 'Sensitive' },
      { value: 'male', label: 'Male speech' },
      { value: 'fem', label: 'Female speech' },
    ],
  },
  {
    key: 'usage',
    label: 'Usage & frequency',
    tags: [
      { value: 'uk', label: 'Usually kana' },
      { value: 'abbr', label: 'Abbreviation' },
      { value: 'quote', label: 'Quotation' },
      { value: 'rare', label: 'Rare' },
      { value: 'dated', label: 'Dated' },
      { value: 'hist', label: 'Historical' },
      { value: 'arch', label: 'Archaic' },
      { value: 'obs', label: 'Obsolete' },
    ],
  },
];

export const allPosTags: { value: string; label: string }[] = posCategories.flatMap((c) => c.tags);
